import { CourseWithHierarchy, Course, Profile } from '@/types/database'

export const DEMO_PROFILE: Profile = {
  id: 'demo-user-id',
  full_name: 'Docente Demo',
  first_name: 'Docente',
  last_name: 'Demo',
  avatar_url: null,
  role: 'student',
  created_at: new Date().toISOString(),
}

export const DEMO_COURSES: CourseWithHierarchy[] = [
  {
    id: 'c1-pedagogia-critica',
    title: 'Pedagogía Crítica y Constructivismo',
    slug: 'pedagogia-critica-y-constructivismo',
    description:
      'Domina los fundamentos epistemológicos y metodológicos de la pedagogía crítica y el constructivismo aplicados al aula y a las evaluaciones del magisterio colombiano. Análisis de Paulo Freire, Piaget, Vygotsky y Ausubel.',
    short_description: 'Evolución pedagógica, modelos constructivistas y aplicación en la práctica docente.',
    thumbnail_url: '/placeholder.jpg',
    price: 0,
    published: true,
    featured: true,
    level: 'Intermedio',
    category: 'Pedagogía',
    instructor_name: 'Dra. Elena Restrepo',
    instructor_role: 'Ph.D en Ciencias de la Educación',
    duration_hours: 5,
    created_at: '2025-01-10T00:00:00Z',
    modules: [
      {
        id: 'mod-1',
        course_id: 'c1-pedagogia-critica',
        title: 'Módulo 1: Fundamentos y Epistemología',
        description: 'Bases teóricas de la pedagogía moderna y concepción del conocimiento.',
        order_index: 1,
        created_at: '2025-01-10T00:00:00Z',
        lessons: [
          {
            id: 'les-1',
            module_id: 'mod-1',
            title: 'Fundamentos Epistemológicos de la Pedagogía',
            description: 'Exploración de los paradigmas epistemológicos clásicos y contemporáneos.',
            order_index: 1,
            video_provider: 'youtube',
            video_id: 'dQw4w9WgXcQ',
            duration_seconds: 2700,
            is_preview: true,
            published: true,
            created_at: '2025-01-10T00:00:00Z',
            materials: [
              {
                id: 'mat-1',
                lesson_id: 'les-1',
                title: 'Lectura Fundamental: Epistemología Educativa (PDF)',
                file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
                file_type: 'pdf',
                file_size: 1048576,
                is_free: true,
                created_at: '2025-01-10T00:00:00Z',
              },
            ],
            progress: {
              id: 'p-1',
              user_id: 'demo-user-id',
              lesson_id: 'les-1',
              completed: true,
              watched_seconds: 2700,
              last_position_seconds: 2700,
              updated_at: '2025-01-11T00:00:00Z',
            },
          },
          {
            id: 'les-2',
            module_id: 'mod-1',
            title: 'Corrientes Pedagógicas del Siglo XX',
            description: 'De la escuela tradicional a la escuela activa y el pensamiento crítico.',
            order_index: 2,
            video_provider: 'youtube',
            video_id: 'dQw4w9WgXcQ',
            duration_seconds: 2280,
            is_preview: true,
            published: true,
            created_at: '2025-01-10T00:00:00Z',
            materials: [],
            progress: {
              id: 'p-2',
              user_id: 'demo-user-id',
              lesson_id: 'les-2',
              completed: true,
              watched_seconds: 2280,
              last_position_seconds: 2280,
              updated_at: '2025-01-12T00:00:00Z',
            },
          },
        ],
      },
      {
        id: 'mod-2',
        course_id: 'c1-pedagogia-critica',
        title: 'Módulo 2: Constructivismo en el Aula',
        description: 'Postulados de Piaget, Vygotsky y Ausubel en la práctica pedagógica real.',
        order_index: 2,
        created_at: '2025-01-10T00:00:00Z',
        lessons: [
          {
            id: 'les-3',
            module_id: 'mod-2',
            title: 'Constructivismo: Piaget, Vygotsky y Ausubel',
            description: 'Zona de Desarrollo Próximo y aprendizaje significativo en acción.',
            order_index: 1,
            video_provider: 'youtube',
            video_id: 'dQw4w9WgXcQ',
            duration_seconds: 3120,
            is_preview: false,
            published: true,
            created_at: '2025-01-10T00:00:00Z',
            materials: [
              {
                id: 'mat-2',
                lesson_id: 'les-3',
                title: 'Cuadro Comparativo: Piaget vs Vygotsky (PDF)',
                file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
                file_type: 'pdf',
                file_size: 524288,
                is_free: false,
                created_at: '2025-01-10T00:00:00Z',
              },
            ],
            progress: {
              id: 'p-3',
              user_id: 'demo-user-id',
              lesson_id: 'les-3',
              completed: true,
              watched_seconds: 3120,
              last_position_seconds: 3120,
              updated_at: '2025-01-13T00:00:00Z',
            },
          },
          {
            id: 'les-4',
            module_id: 'mod-2',
            title: 'Pedagogía Crítica — Freire y McLaren',
            description: 'La educación problematizadora frente a la educación bancaria.',
            order_index: 2,
            video_provider: 'youtube',
            video_id: 'dQw4w9WgXcQ',
            duration_seconds: 2460,
            is_preview: false,
            published: true,
            created_at: '2025-01-10T00:00:00Z',
            materials: [
              {
                id: 'mat-3',
                lesson_id: 'les-4',
                title: 'Guía de Preguntas Generadoras en el Aula (PDF)',
                file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
                file_type: 'pdf',
                file_size: 786432,
                is_free: false,
                created_at: '2025-01-10T00:00:00Z',
              },
            ],
            progress: {
              id: 'p-4',
              user_id: 'demo-user-id',
              lesson_id: 'les-4',
              completed: false,
              watched_seconds: 1200,
              last_position_seconds: 1200,
              updated_at: '2025-01-14T00:00:00Z',
            },
          },
        ],
      },
      {
        id: 'mod-3',
        course_id: 'c1-pedagogia-critica',
        title: 'Módulo 3: Evaluación y Neurociencia',
        description: 'Evaluación formativa por competencias y bases neurocientíficas del aprendizaje.',
        order_index: 3,
        created_at: '2025-01-10T00:00:00Z',
        lessons: [
          {
            id: 'les-5',
            module_id: 'mod-3',
            title: 'Evaluación Formativa por Competencias',
            description: 'Rúbricas, retroalimentación dialógica y evaluación auténtica.',
            order_index: 1,
            video_provider: 'youtube',
            video_id: 'dQw4w9WgXcQ',
            duration_seconds: 2100,
            is_preview: false,
            published: true,
            created_at: '2025-01-10T00:00:00Z',
            materials: [],
            progress: null,
          },
          {
            id: 'les-6',
            module_id: 'mod-3',
            title: 'Neurociencia y Plasticidad en el Aprendizaje',
            description: 'Cómo aprende el cerebro y estrategias cognitivas comprobadas.',
            order_index: 2,
            video_provider: 'youtube',
            video_id: 'dQw4w9WgXcQ',
            duration_seconds: 2880,
            is_preview: false,
            published: true,
            created_at: '2025-01-10T00:00:00Z',
            materials: [],
            progress: null,
          },
        ],
      },
    ],
  },
  {
    id: 'c2-decreto-1278',
    title: 'Decreto 1278: Marco Legal y Concurso Docente',
    slug: 'decreto-1278-marco-legal-docente',
    description:
      'Comprende a fondo el Estatuto de Profesionalización Docente (Decreto Ley 1278 de 2002), el sistema de evaluación de competencias, derechos, deberes y preparación estratégica para la prueba del MEN.',
    short_description: 'Estatuto 1278, escalafón docente, evaluación de desempeño y concurso de méritos.',
    thumbnail_url: '/placeholder.jpg',
    price: 49900,
    published: true,
    featured: true,
    level: 'Avanzado',
    category: 'Legislación',
    instructor_name: 'Abg. Carlos Andrés Medina',
    instructor_role: 'Especialista en Derecho Administrativo y Educativo',
    duration_hours: 8,
    created_at: '2025-01-15T00:00:00Z',
    modules: [],
  },
  {
    id: 'c3-evaluacion-formativa',
    title: 'Evaluación del Aprendizaje y Diseño de Ítems',
    slug: 'evaluacion-aprendizaje-diseno-items',
    description:
      'Metodología para la formulación de preguntas por competencias según estándares del ICFES y el MEN. Validez, confiabilidad y análisis de distractores en pruebas objetivas.',
    short_description: 'Construcción de preguntas por competencias, juicio de expertos y análisis psicométrico.',
    thumbnail_url: '/placeholder.jpg',
    price: 39900,
    published: true,
    featured: true,
    level: 'Intermedio',
    category: 'Evaluación',
    instructor_name: 'Mg. Martha Lucía Gómez',
    instructor_role: 'Asesora en Evaluación Educativa',
    duration_hours: 6,
    created_at: '2025-01-20T00:00:00Z',
    modules: [],
  },
]
